
export { default as AddRate } from './AddRate'
export { default as AddUser } from './AddUser'
export { default as Attributes } from './Attributes'
export { default as Categories } from './Categories'
export { default as CreateAttribute } from './CreateAttribute'
export { default as CreateCategory } from './CreateCategory'
export { default as CreateCurrency } from './CreateCurrency'
export { default as CreateOrder } from './CreateOrder'
export { default as CreateProduct } from './CreateProduct'
export { default as CreateRoles } from './CreateRoles'
export { default as Currencies } from './Currencies'
export { default as Dashboard } from './Dashboard'
export { default as EditAttribute } from './EditAttribute'
export { default as EditCategory } from './EditCategory'
export { default as EditProduct } from './EditProduct'
export { default as EditRole } from './EditRole'
export { default as EditUser } from './EditUser'
export { default as ErrorPage } from './ErrorPage'
export { default as HomeLayout } from './HomeLayout'
export { default as Landing } from './Landing'
export { default as Login } from './Login'
export { default as OrderList } from './OrderList'
export { default as Products } from './Products'
export { default as Profile } from './Profile'
export { default as Register } from './Register'
export { default as Roles } from './Roles'
export { default as Settings } from './Settings'
export { default as SingleErrorPage } from './SingleErrorPage'
export { default as UserRole } from './UserRole'
export { default as Users } from './Users'
export { default as ViewAttribute } from './ViewAttribute'
export { default as ViewCategory } from './ViewCategory'
export { default as ViewProduct } from './ViewProduct'
export { default as ViewRole } from './ViewRole'
export { default as ViewUser } from './ViewUser'




